<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-11-17 21:07

$extensionPath = t3lib_extMgm::extPath('tablecleaner');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_tablecleaner_controller_infomodulecontroller' => $extensionClassesPath . 'Controller/InfoModuleController.php',
	'tx_tablecleaner_domain_model_page' => $extensionClassesPath . 'Domain/Model/Page.php',
	'tx_tablecleaner_domain_repository_pagerepository' => $extensionClassesPath . 'Domain/Repository/PageRepository.php',
	'tx_tablecleaner_tasks_base' => $extensionClassesPath . 'Tasks/Base.php',
	'tx_tablecleaner_tasks_deleted' => $extensionClassesPath . 'Tasks/Deleted.php',
	'tx_tablecleaner_tasks_deletedadditionalfieldprovider' => $extensionClassesPath . 'Tasks/DeletedAdditionalFieldProvider.php',
	'tx_tablecleaner_tasks_expired' => $extensionClassesPath . 'Tasks/Expired.php',
	'tx_tablecleaner_tasks_expiredadditionalfieldprovider' => $extensionClassesPath . 'Tasks/ExpiredAdditionalFieldProvider.php',
	'tx_tablecleaner_tasks_paststoptime' => $extensionClassesPath . 'Tasks/PastStopTime.php',
	'tx_tablecleaner_tasks_paststoptimeadditionalfieldprovider' => $extensionClassesPath . 'Tasks/PastStopTimeAdditionalFieldProvider.php',
	'tx_tablecleaner_tasks_hidden' => $extensionClassesPath . 'Tasks/Hidden.php',
	'tx_tablecleaner_tasks_hiddenadditionalfieldprovider' => $extensionClassesPath . 'Tasks/HiddenAdditionalFieldProvider.php',
	'tx_tablecleaner_utility_base' => $extensionClassesPath . 'Utility/Base.php',
	'tx_tablecleaner_viewhelpers_format_rawviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/RawViewHelper.php',
	'tx_tablecleaner_viewhelpers_format_replaceviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/ReplaceViewHelper.php',
);
?>