<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-14 11:44

$extensionPath = t3lib_extMgm::extPath('tablecleaner');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_tablecleaner_tasks_clean' => $extensionClassesPath . 'Tasks/Clean.php',
	'tx_tablecleaner_tasks_cleanadditionalfieldprovider' => $extensionClassesPath . 'Tasks/CleanAdditionalFieldProvider.php',
	'tx_tablecleaner_tasks_truncate' => $extensionClassesPath . 'Tasks/Truncate.php',
	'tx_tablecleaner_tasks_truncateadditionalfieldprovider' => $extensionClassesPath . 'Tasks/TruncateAdditionalFieldProvider.php',
);
?>