<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-10-17 19:54

$extensionPath = t3lib_extMgm::extPath('tablecleaner');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_tablecleaner_tasks_base' => $extensionClassesPath . 'Tasks/Base.php',
	'tx_tablecleaner_tasks_deleted' => $extensionClassesPath . 'Tasks/Deleted.php',
	'tx_tablecleaner_tasks_deletedadditionalfieldprovider' => $extensionClassesPath . 'Tasks/DeletedAdditionalFieldProvider.php',
	'tx_tablecleaner_tasks_expired' => $extensionClassesPath . 'Tasks/Expired.php',
	'tx_tablecleaner_tasks_expiredadditionalfieldprovider' => $extensionClassesPath . 'Tasks/ExpiredAdditionalFieldProvider.php',
	'tx_tablecleaner_tasks_hidden' => $extensionClassesPath . 'Tasks/Hidden.php',
	'tx_tablecleaner_tasks_hiddenadditionalfieldprovider' => $extensionClassesPath . 'Tasks/HiddenAdditionalFieldProvider.php',
);
?>